## NUMPY LIBRARY

Data that we deal with comes in various shapes and form and originate from various sources, however at the end all of them can be fundamentally represented as array of Numeric digits

Some example as follows:

- Data that are fundamentally numeric(Financial Transaction amount, Your Monthly income, number of time visited in a website last 7 days) 
- sound: Stored as a one dimensional array of frequency vs time
- Images: Stored as a two dimensional numeric arrays representing business values of each pixel over an area
- Text: can be represented as numeric digits as well in various ways 

In [1]:
# Need to import Numpy Library to use it
import numpy as np

##### Creating Array

In [1]:
# Create a numpy library from Tuple
import numpy as np
arr = np.array([[8,9,7,6,5],[1,3,4,5,6],[12,11,13,14,15]])
print("Print first Numpy Array::--", arr)
print("Print Shape Numpy Array::--", arr.shape)

Print first Numpy Array::-- [[ 8  9  7  6  5]
 [ 1  3  4  5  6]
 [12 11 13 14 15]]
Print Shape Numpy Array::-- (3, 5)


In [18]:
# Create an arrays of all zeroes

arr = np.zeros((4,4))
print(arr)
print("Print Shape Numpy Array of zeros::--",arr.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Print Shape Numpy Array of zeros::-- (4, 4)


In [19]:
# Create an arrays of all ones
arr = np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
# Create an arrays filling all elements with a specified values
arr = np.full((4,3),10)
print(arr)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]


In [23]:
# create a 4 x 4 identity matrix
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
# create an array with random values
arr = np.random.random((3,3))
print(arr)

[[0.44675288 0.85038456 0.61210782]
 [0.81308052 0.17383382 0.62193411]
 [0.84419028 0.11111603 0.68923439]]


In [2]:
# Create an array  with sequential values staring from 0 to a given range limit
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
# Create an array  with sequential values staring from 0 to a final value and with a step value
arr = np.arange(3, 30, 2)
arr

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [31]:
# Reshape the Array to a new specified dimension
arr = np.arange(30)
arr = arr.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
# Reshape the Array to a new specified dimension - shorter way
arr = np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [35]:
# Creating a String Array
arr = np.array([['John','Lean'],['Sham', 'Shaun']])
arr

array([['John', 'Lean'],
       ['Sham', 'Shaun']], dtype='<U5')

In [7]:
# Return the dot products of two arrays
arr1 = np.arange(30).reshape(5,6)
print(arr1)
arr2 = arr1.T
print(arr2)
arr_res = arr1.dot(arr2)
print(arr_res)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]
[[  55  145  235  325  415]
 [ 145  451  757 1063 1369]
 [ 235  757 1279 1801 2323]
 [ 325 1063 1801 2539 3277]
 [ 415 1369 2323 3277 4231]]


In [5]:
# Find the Min, Max, Mean, Standard Deviation and Variance of the elements
arr1 = np.arange(30).reshape(5,6)
minm = arr1.min()
maxm = arr1.max()
mean = arr1.mean()
std = arr1.std(axis = 1) # Along the column
var = arr1.var(axis = 0) # Along the rows
print("Minimum:- ",minm)
print("Maximum:- ",maxm)
print("Mean:- ",mean)
print("Standard Deviation:- ",std)
print("Variance:- ",var)

Minimum:-  0
Maximum:-  29
Mean:-  14.5
Standard Deviation:-  [1.70782513 1.70782513 1.70782513 1.70782513 1.70782513]
Variance:-  [72. 72. 72. 72. 72. 72.]


In [8]:
# create copy
arr1 = np.arange(30).reshape(5,6)
arrc = arr1.copy()
print(arrc)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [10]:
# Rounding Elements
arr1 = np.random.random((3,3))
print("ARRAY 1: \n",arr1)
arr2 = arr1.round(2)
print("ARRAY 2: \n",arr2)

ARRAY 1: 
 [[0.83162605 0.30597282 0.88854935]
 [0.83408152 0.14292317 0.08264393]
 [0.55461476 0.65312932 0.7788924 ]]
ARRAY 2: 
 [[0.83 0.31 0.89]
 [0.83 0.14 0.08]
 [0.55 0.65 0.78]]


In [12]:
# Converting data Types with astypes
arr1 = np.arange(30).reshape(5,6)
print("ARRAY 1: \n",arr1)
arr2 = arr1.astype(str)
print("ARRAY 2: \n",arr2)
arr3 = arr1.astype(int)
print("ARRAY 3: \n",arr3)

ARRAY 1: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
ARRAY 2: 
 [['0' '1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '10' '11']
 ['12' '13' '14' '15' '16' '17']
 ['18' '19' '20' '21' '22' '23']
 ['24' '25' '26' '27' '28' '29']]
ARRAY 3: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


## Accessing Array Elements

In [33]:
# Accessing array elements 2nd row, 3rd column
arr1 = np.arange(30).reshape(5,6)
print("ARRAY 1: \n",arr1)
print("Print Element at the 2nd Row 3rd column: \n",arr1[2,2])

ARRAY 1: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Print Element at the 2nd Row 3rd column: 
 14


In [19]:
# Accessing array elements 
arr1 = np.arange(30).reshape(5,6)
print("ARRAY 1: \n",arr1)
print("Print Element at the 2nd Row 3rd column: \n",arr1[2,2])
print("All Elements at the 2nd Row: \n",arr1[1])
print("Elements at the 3rd column: \n",arr1[:,2])
print("All Elements: \n",arr1[:,:])

ARRAY 1: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Print Element at the 2nd Row 3rd column: 
 14
All Elements at the 2nd Row: 
 [ 6  7  8  9 10 11]
Elements at the 3rd column: 
 [ 2  8 14 20 26]
All Elements: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [2]:
# Accessing array elements by its position
arr1 = np.arange(30).reshape(5,6)
print("ARRAY 1: \n",arr1)
print("Print Element at the 2nd Row 3rd to 5th position: \n", arr1[1, 2:5])
print("Elements at the 3rd column 3rd to 5th row position: \n",arr1[2:5, 2])
print("Print Element at the 2nd Row 3rd to 5th position, Elements at the 3rd column 3rd to 5th row position::--\n",arr1[2:5, 2:5])

ARRAY 1: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Print Element at the 2nd Row 3rd to 5th position: 
 [ 8  9 10]
Elements at the 3rd column 3rd to 5th row position: 
 [14 20 26]
Print Element at the 2nd Row 3rd to 5th position, Elements at the 3rd column 3rd to 5th row position::--
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


#### Iterating thru an arrays

In [4]:
# Iterating thru Rows
arr1 = np.arange(30).reshape(5,6)
print("Printing thru rows::--")
for row in arr1:
    print(row)
# Iterating thru rows
print("Printing thru columns::--")
cols = arr1.shape[1]
for n in range(cols):
    print(arr1[:,n])

Printing thru rows::--
[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
Printing thru columns::--
[ 0  6 12 18 24]
[ 1  7 13 19 25]
[ 2  8 14 20 26]
[ 3  9 15 21 27]
[ 4 10 16 22 28]
[ 5 11 17 23 29]


#### Stacking  arrays

In [8]:
#Horizontal Stacking of Two Arrays
arr1 = np.arange(30).reshape(5,6)
print("ARRAY 1: \n",arr1)
arr2 = np.arange(100, 130).reshape(5,6)
print("ARRAY 2: \n",arr2)
print("Stacked Array Horizontal:::--\n",np.hstack((arr1,arr2)))
print("Stacked Array Vertical:::--\n",np.vstack((arr1,arr2)))

ARRAY 1: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
ARRAY 2: 
 [[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]
 [124 125 126 127 128 129]]
Stacked Array Horizontal:::--
 [[  0   1   2   3   4   5 100 101 102 103 104 105]
 [  6   7   8   9  10  11 106 107 108 109 110 111]
 [ 12  13  14  15  16  17 112 113 114 115 116 117]
 [ 18  19  20  21  22  23 118 119 120 121 122 123]
 [ 24  25  26  27  28  29 124 125 126 127 128 129]]
Stacked Array Vertical:::--
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]
 [ 24  25  26  27  28  29]
 [100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]
 [124 125 126 127 128 129]]


#### Spliting  arrays

In [16]:
# Vertical Spliting of two Arrays
arr1 = np.arange(36).reshape(6,6)
print("ARRAY 1:\n",arr1, '\n')
splt = np.vsplit(arr1, 2)
print(splt[0], '\n')
print(splt[1])

ARRAY 1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 

[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [17]:
# Horizontal Spliting of two Arrays
arr1 = np.arange(36).reshape(6,6)
print("ARRAY 1:\n",arr1, '\n')
splt = np.hsplit(arr1, 2)
print(splt[0], '\n')
print(splt[1])

ARRAY 1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]] 

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]
 [24 25 26]
 [30 31 32]] 

[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]


## Array Assignment vs copy

In [18]:
# Demonstrate Array Assignment
arr1 = np.arange(36).reshape(6,6)
arr2 = arr1
arr1[1,1] = 99
print("ARRAY 1:\n",arr1)
print("ARRAY 2:\n",arr2)

ARRAY 1:
 [[ 0  1  2  3  4  5]
 [ 6 99  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
ARRAY 2:
 [[ 0  1  2  3  4  5]
 [ 6 99  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [19]:
# Demonstrate Array Copy
arr1 = np.arange(36).reshape(6,6)
arr2 = arr1.copy()
arr1[1,1] = 99
print("ARRAY 1:\n",arr1)
print("ARRAY 2:\n",arr2)

ARRAY 1:
 [[ 0  1  2  3  4  5]
 [ 6 99  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
ARRAY 2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
